ban_url: "https://discord.gg/MTYrSgVkmd"

filtered-stuff:
  - "nigger"
  - "nigga"
  - "niggerfaggot"
  - "faggot"
  - "heil hitler"
  - "h3il h1tl3r"
  - "sieg heil"
  - "s1eg h3il"
  - "gas the jews"
  - "gas die juden"
  - "sterbe in der gaskammer"
  - "sterbe in der gas kammer"
  - "gas the kikes"
  - "gas die kikes"
  - "race war now"
  - "heil fuhrer"
  - "heil führer"
  - "nіggеr"
  - "jigaboo"
  - "white power"