ban_url: "https://discord.gg/MTYrSgVkmd"

filtered-stuff:
  - "nigger"
  - "nigga"
  - "faggot"
  - "tranny"
  - "kike"
  - "jigaboo"
  - "polack"
  - "heil hitler"
  - "sieg heil"
  - "nіggеr"
  - "ոіggеr"
  - "white power"